domain:
  name: Swimmer
  episodes: 1000
DDPG:
  gamma: 0.95
  tau: 0.01
  N: 100 #mini match size
  experience_replay_buffer_size: 100000
  noise_var: 0.1 # variance of the action process for exploration
  optimizer_gamma: 0.001 # the learning rate of the optimizers